name: R Package CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "feature/**"  # Run on any branch starting with 'feature/'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          R -e 'install.packages("pak")'
          R -e 'pak::pak()'

      - name: Build the package
        run: R CMD build .

      - name: Check the package
        run: R CMD check --as-cran $(ls *.tar.gz)

      - name: Install the package
        run: R CMD INSTALL $(ls *.tar.gz)
